version: '3.8'

services:
  # Database (same as production)
  database:
    image: mongo:7.0
    container_name: sponsorconnect-db-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sponsorconnect
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sponsorconnect-network-dev

  # Backend with hot reload
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sponsorconnect-backend-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://admin:password123@database:27017/sponsorconnect?authSource=admin
      - JWT_SECRET=dev-secret-key
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - sponsorconnect-network-dev

  # Frontend with hot reload
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sponsorconnect-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-dev
    networks:
      - sponsorconnect-network-dev

volumes:
  mongodb_data_dev:
    driver: local

networks:
  sponsorconnect-network-dev:
    driver: bridge
